services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
      - POSTGRES_USER=rishav
      - POSTGRES_PASSWORD=YOuWYelw5p4leqy
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: rishavkapil61@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin@8454
      PGADMIN_DEFAULT_SERVER: postgres_db:5432
    ports:
      - "38080:80"
volumes:
  postgres_db:
    driver: local
